---
author: "Prashant Kalvapalle"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

---
title: `r title_name`
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F) #, fig.width = 10, fig.height = 5)
```

## Goal of the analysis

We want to test by qPCR if AHL is flipping any constructs. Using this file to normalize copy #s to that of the Backbone

## Cq Plots

``` {r cq_plt}
plt.cq

plotly::ggplotly(plt.cq)

if(exists('plt.cq_w.std')) plt.cq_w.std

```

## Copies plot
``` {r copies1}

plt.copies


if(exists('plt.copies_w.mean')) plt.copies_w.mean

if(exists('plt.copies_w.mean')) format_logscale_y(plt.copies_w.mean) %>% print

```

## Melting temp

### Tm1

Largest melting temperature peak
```{r tm1}
plt.tm1

plotly::ggplotly(plt.tm1)

if(exists('plt.tm1_w.std')) plt.tm1_w.std

```

### All Tm peaks

All peaks of melting temperature
```{r alltm}
plt.alltm

plt.alltm_2

```

## Data output

```{r datadisplay}
absolute_dat %>% 
  
  # Select only mean copies
  select(Target_name, assay_var.label, mean_Copies.per.ul.template, Sample_category) %>% 
    distinct() %>% # Remove replicates
  mutate(across(assay_var.label, ~ str_replace(., '\n', ' '))) %>% # replace new lines with space
  mutate_if(is.numeric, format, digits = 3, scientific = T) %>% # format scientific with 2 decimal plates
kable(., caption = 'Mean data') # format table for clean output
```

<!-- ## Transforming data and normalization -->

<!-- 1. Select only relevant data from the results -->
<!-- 2. Data divided into 3 tibbles for each primer-pair (also called as Target) -->


<!-- 3. Ratio of Flipped/Backbone and Unflipped/backbone are calculated -->

<!-- 4. data is combined into 1 data frame -->
<!-- 5. And plotted in next section -->

<!-- ```{r} -->
<!-- # sel <- results_abs %>% select(`Sample Name`,assay_variable,`Primer pair`,Target,`Copy #`) -->
<!-- # # sel_grouped <- sel %>% group_by(Target) %>% mutate(id = 1:n()) -->
<!-- # # sel_spread <- sel_grouped %>% spread(Target,`Copy #`) -->
<!-- #  -->
<!-- #  -->
<!-- # sel_b <- sel %>% filter(Target == 'Backbone') -->
<!-- # sel_f <- sel %>% filter(Target == 'Flipped'); sel_u <- sel %>% filter(Target == 'Unflipped'); -->
<!-- #  -->
<!-- # sel_f %<>% mutate("Normalized copy #" = sel_f$`Copy #`/sel_b$`Copy #`);  -->
<!-- # sel_u %<>% mutate("Normalized copy #" = sel_u$`Copy #`/sel_b$`Copy #`); -->
<!-- #  -->
<!-- # results_ratio <- bind_rows(sel_f, sel_u)   -->
<!-- ``` -->

<!-- ## Including Plots -->

<!-- Plots here -->

<!-- ```{r pressure, echo=FALSE} -->

<!-- # plt_norm <- results_ratio %>% ggplot(aes(x = `assay_variable`, y = `Normalized copy #`, color = Target)) +   # plotting -->
<!-- #   scale_y_log10(  # logscale for y axis with tick marks -->
<!-- #     breaks = scales::trans_breaks("log10", function(x) 10^x), -->
<!-- #     labels = scales::trans_format("log10", scales::math_format(10^.x) ) -->
<!-- #   ) -->
<!-- #  -->
<!-- # plt_norm <- plt_norm + geom_point(size = 2) + -->
<!-- #     theme_classic() + scale_color_brewer(palette="Set1") +  -->
<!-- #     theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 90, hjust = 1, vjust = .3)) +  -->
<!-- #     ggtitle(title_name) + facet_wrap(~`Sample Name`, scales = 'free_x') -->
<!-- #  -->
<!-- # print(plt_norm) -->
<!-- # ggsave('S5a_AHL flip_normalized.png') -->

<!-- ``` -->