---
title: "WW21_601 redo + TR2"
author: "Prashant Kalvapalle"
date: "27 June 2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.width = 12, fig.height = 4)

# Loading libraries, functions and user inputs
source('./general_functions.R') # Source the general_functions file
source('./inputs_for_analysis.R') # Source the file with user inputs


# Spike in and concentration details
HA_concentration_factor <- 500 # concentration factor of wastewater -> RNA
spike_virus_conc <- 5495.44 # copies/ul viral suspension spiked in (Spike ID: S12)
spike_virus_volume <- 50 # ul of viral suspension spiked in x ml WW; (x ~ 350 - 450 and varies for each sample)

# sheets to read from qPCR data dump excel file
read_these_sheets <- c('WW21_TR2 622') # sheet name(s) in the raw data file (qPCR data dump) - Separate by comma (,)
title_name <- '622 TR2_a' # name of the filename for writing presentable data and plot title

# Biobot ID sheet to draw sample names from
bb_sheets <- c('Week 8 (6/1)')

# Extra categories for plotting separately (separate by | like this 'Vaccine|Troubleshooting')
extra_categories = 'TR2' # for excluding this category from a plot, make the switch (exclude_sample = TRUE)

# To rename samples with descriptive category/names (usually for extra TR experiments)
# - For other samples: Make it empty an string (like this '' ) to avoid messing up names inadvertantly
translate_id_manual <- c('WW/Field', 'Water/Field', 'WW/Lab',  'Water/Lab', 'Solids/Present', 'Solids/Removed', 'Bead-beating/Dilter', 'Bead-beating/No filter') %>% setNames(str_c('^', c('A','B','C','D','E','F','G','H'))) 
```

## Goal of the analysis

Quantifying CoV2-N1,N2 (multiplexed) and BCoV spike in in 6/8 wastewater samples

## Plots with raw names

### Individual biological replicates

```{r scripts, fig.width = 12}

# Acquire all the pieces of the data : read saved raw qPCR results from a google sheet
list_rawqpcr <- map(read_these_sheets, ~ read_sheet('https://docs.google.com/spreadsheets/d/1ouk-kCJHERRhOMNP07lXfiC3aGB4wtWXpnYf5-b2CI4/edit#gid=0', sheet = ., range = 'A:H')) 

rawqpcr <- bind_rows(list_rawqpcr)
results_abs <- rawqpcr %>% filter(!str_detect(`Sample Name`, '/')) # remove Baylor samples (5/26 and 6/2) - processed separately


# plot individual biological replicates
map2(list_rawqpcr, read_these_sheets, ~(plot_biological_replicates(.x, title_text = .y)))

```

### Summary plot

```{r summary}

summary_results_abs <- results_abs %>% group_by(Target, `Sample Name`, assay_variable) %>% summarise_at('Copy #', funs(mean(.,na.rm = T), sd(., na.rm = T)))

# plot copy # vs sample (assay_variable)
plot_mean_sd_jitter(summary_data = summary_results_abs, raw_data = results_abs, long_format = F) %>% format_logscale_y() %>% print()
```

## Plots (WWTP labels)

### Summary plot

```{r biobot_to_WWTP}

# Bring WWTP names from google sheet: "Biobot Sample IDs"
biobot_lookup <- map_df(bb_sheets , ~ read_sheet('https://docs.google.com/spreadsheets/d/1ghb_GjTS4yMFbzb65NskAlm-2Gb5M4SNYi4FHE4YVyI/edit#gid=233791008', sheet = .x, range = 'H:J')) %>% rename('Biobot ID' = contains('Biobot', ignore.case = T), 'WWTP' = SYMBOL) %>% mutate('Biobot ID' = str_remove(`Biobot ID`,'\\.'), WWTP = as.character(WWTP))

# polishing qPCR data - Make Biobot ID column clean
qpcr_polished <- results_abs %>% unite('Biobot ID', c(`Sample Name`, assay_variable), sep = '', remove = F) %>%
  select(-`Well Position`) %>% 
  mutate_at('assay_variable', as.character) %>% 
  mutate_at('biological_replicates', ~str_replace_na(., ''))

# Join WWTP names to qPCR dataset
bb_qpcr <- left_join(qpcr_polished, biobot_lookup, by = 'Biobot ID') %>% mutate_at(c('WWTP', 'FACILITY NAME'), ~if_else(str_detect(., '^X')|is.na(.), assay_variable, .)) %>% 
  mutate_at('Tube ID', ~str_remove(., "\\.")) %>%  unite('Label_tube', c('Sample Name', 'Tube ID'), sep = "", remove = F) # make a unique column for matching volumes

summary_bb_qpcr <- bb_qpcr %>% group_by(Target, `Sample Name`, `FACILITY NAME`, WWTP) %>% summarise_at('Copy #', funs(mean(.,na.rm = T), sd(., na.rm = T)))

WWTP_order_1 <- summary_bb_qpcr %>% filter( str_detect(Target,'BCoV')) %>% arrange(`mean`) %>% pull(WWTP) # order samples by ascending order of BCoV

summary_bb_qpcr$WWTP %<>%  fct_relevel(levels = WWTP_order_1) # order samples by 5/12 ascending order


plot_mean_sd_jitter(summary_bb_qpcr, bb_qpcr, sample_var = extra_categories, exclude_sample = T, x_var = WWTP) %>% format_logscale_y() %>% print()
```

### Recovery

open circles : Viral copies spiked in
```{r Recovery_calculations}

# Get volumes data from google sheet : "Sample registry"
volumes_data <- read_sheet('https://docs.google.com/spreadsheets/d/1mJcCt1wMiOuBic6sRlBZJf8KSNu2y-B5PjzCUu7jPM8/edit#gid=521099478', sheet = 'Concentrated samples', range = 'A:D') %>% 
  rename('WW_vol' = `Total WW vol measured (ml)`, 'Label_tube' = `Label on tube`) %>% 
  select(WW_vol, Label_tube) %>% 
  fill(WW_vol) %>% distinct() %>% 
  mutate_at('Label_tube', ~str_remove_all(., " "))
  
# join the results with the WWTP identifiers and names
vol_qpcr <- bb_qpcr %>% left_join(volumes_data, by = 'Label_tube') %>% 
  # Calculations for spiked in and recovered copies of the virus
  mutate(`Actual spike-in` = spike_virus_conc * spike_virus_volume / (WW_vol * 1e-3), Recovered = `Copy #` * 1e6/HA_concentration_factor, `Recovery fraction` = 100 * Recovered/`Actual spike-in`) %>% 
  mutate_cond(str_detect(`Sample Name`, 'Vaccine'), `Actual spike-in` = spike_virus_conc * spike_virus_volume / (.050 * 1e-3), Recovered = `Copy #` * 1e6/1, `Recovery fraction` = 100 * Recovered/`Actual spike-in`)
 
```


```{r summarizing_plot}

spike_qpcr <- vol_qpcr %>% filter(str_detect(Target, 'BCoV|BRSV')) %>% select(-c(3,4,6,7,8)) %>% 
  mutate_at(c('WWTP', 'FACILITY NAME'), ~str_replace_all(., translate_id_manual)) %>% 
  separate(WWTP, c('WWTP', 'tmp')) %>% 
  mutate_cond(str_detect(`Sample Name`, 'TR'), 'Sample Name' = WWTP, 'WWTP' = tmp) %>% 
  select(-tmp)

vol_qpcr_summary <- spike_qpcr %>% select(-WW_vol) %>% group_by(Target, `Sample Name`, `FACILITY NAME`, WWTP) %>% summarise_at(vars(2,3:5), funs(mean(.,na.rm = T), sd(.,na.rm = T))) # Summarize mean and SD for biological replicates

WWTP_order <- vol_qpcr_summary %>% filter(`Sample Name` == '608', str_detect(Target,'BCoV')) %>% arrange(`Copy #_mean`) %>% pull(WWTP) # order samples by 5/12 ascending order

vol_qpcr_summary$WWTP %<>%  fct_relevel(levels = WWTP_order) # order samples by 5/12 ascending order

long_vol_qpcr_summary <- vol_qpcr_summary %>% gather(key = 'Measurement', value = 'Reading', -Target, -`Sample Name`, -`FACILITY NAME`, -WWTP) %>% separate(Measurement, into = c('Measurement','val'),"_") %>% spread(val,Reading) # Seperate mean and variance and group by variable of measurement

long_vol_qpcr_raw <- spike_qpcr %>% gather(key = 'Measurement', value = 'val', -Target, -`Sample Name`, -WWTP, -`FACILITY NAME`) # Seperate mean and variance and group by variable of measurement

# plot recovery and spiked in
reco_plot <- plot_mean_sd_jitter(long_vol_qpcr_summary, long_vol_qpcr_raw, long_format = T, measure_var = 'Recovered', sample_var = extra_categories, exclude_sample = T, x_var = WWTP, ylabel = 'Genome copies/l Wastewater') + geom_point(data = filter(long_vol_qpcr_summary, str_detect(Measurement,'Actual')), colour = 'black', shape = 21) + geom_line(data = filter(long_vol_qpcr_summary, str_detect(Measurement,'Actual')), colour = 'black')

reco_plot %>%  format_logscale_y() %>% print()
```

### % recovery

```{r percentreco}

plot_mean_sd_jitter(long_vol_qpcr_summary, long_vol_qpcr_raw, sample_var = extra_categories, exclude_sample = T, long_format = T,  measure_var = 'Recovery fraction', x_var = WWTP, ylabel = 'Fraction of spike-in recovered') %>% print()
```

## Special categories

### Summary plot




## Data output

```{r summarydatadisplay}
presentable_vol_qpcr <- vol_qpcr %>% rename('Facility' = `FACILITY NAME`) %>% 
  mutate_at('Sample Name', ~as.character(.)) %>% 
  mutate_at('Facility', ~if_else(. == assay_variable, str_c(`Sample Name`, '/', assay_variable), .)) %>% 
  mutate_at('Facility', ~str_replace(., '609', 'Extraction blank')) %>% 
  arrange(Facility, biological_replicates) %>% 
  unite('Facility', c(Facility, biological_replicates), sep = "-", na.rm = T) %>% 
  filter(!str_detect(assay_variable, '11|9')) %>% 
  mutate_cond(str_detect(Target, 'N'), `Recovery fraction` = NA, `Actual spike-in` = NA) %>% 
  select(Facility, WWTP, WW_vol, Target, CT, `Copy #`, Recovered, `Actual spike-in`, `Recovery fraction`) %>% 
  rename('Copies/ul RNA' = `Copy #`, 'Copies/l WW' = Recovered, 'Spiked-in Copies/l WW' = `Actual spike-in`)

# presentable data for discussion with Baylor
write_sheet(presentable_vol_qpcr,'https://docs.google.com/spreadsheets/d/1ltvW7xZf2aUPoBchD4NFGuV0gGWPkdsOW3a0Hxalm-Y/edit#gid=2113120147', sheet = title_name)  # save results to a google sheet
  

present_N_data <- presentable_vol_qpcr %>% filter(!str_detect(Facility, "Vaccine|NTC|Blank"), str_detect(Target, "^N")) %>%  # select only N1,N2 - remove distracting data
select(-`Recovery fraction`, -`Spiked-in Copies/l WW`)
# presentable data for health department
write_sheet(present_N_data,'https://docs.google.com/spreadsheets/d/1dBESjgWSFsOBodFFpYNhWIOAQ2a3wvoLkrn12V_rFck/edit#gid=0', sheet = title_name) # save results to a google sheet


# summary_results %<>% mutate_if(is.numeric, format, digits = 3, scientific = T)
# kable(summary_results, caption = 'Summary of estimated copy #s')
```

<!-- ### Individual replicates -->
<!-- ```{r datadisplay} -->
<!-- results_abs %<>% mutate_if(is.numeric, format, digits = 3, scientific = T) -->
<!-- kable(results_abs, caption = 'Raw data and estimated copy #s') -->
<!-- ``` -->
